### ISSUE TITLE
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.24.0

### ISSUE THREAD

**Issue by JeffDeans** [soolaugust/docker-images#5]
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.24.0
这个镜像 帮忙下载

**Comment by JeffDeans** [comment]
@soolaugust 谢谢

**Comment by soolaugust** [comment]
已经解决, 请使用下面的命令尝试:

```shell
./download.sh gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.24.0
```

**Comment by soolaugust** [comment]
https://github.com/all-contributors please add @JeffDeans for talk

**Comment by soolaugust** [comment]
@all-contributors please add @JeffDeans for talk
